[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {git = "https://github.com/tocklime/aoc-rs"}
aoc_harness_macros = {git = "https://github.com/tocklime/aoc-rs"}
aoc_harness = {git = "https://github.com/tocklime/aoc-rs"}
sscanf = "0.1.3"
structopt = "0.3"
seq-macro = "0.2.0"
aocf = "0.1.13"
itertools = "0.10.1"
time = "0.3.5"
rayon = "1.5.1"
bitvec = "0.22.3"
text_io = "0.1.9"
ux = "0.1.0"
bit-array = "0.4.3"
typenum = "1.14.0"
nalgebra = "0.8.0"
derive_more = "0.99.16"
ndarray = "0.15.4"
packed_simd = { version = "0.3.4",package = "packed_simd_2"}
core_simd = { git = "https://github.com/rust-lang/portable-simd" }
criterion = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "aoc"
path = "src/day05.rs"
harness = false

[profile.dev]
opt-level = 3

[profile.release]
debug = false

