name: "Build AoC"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: Swatinem/rust-cache@v1
      - name: aoc-cargo
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          cargo run --bin all
      - name: aoc-cargo-release
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          cargo run --release --bin all
      - name: aoc-nix
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          nix build
          time ./result/bin/all -b
