name: "Build AoC"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - name: aoc
        run: |
          nix build
          time ./result/bin/all -b
