name: "Build AoC"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - name: aoc
        run: |
          nix build
          touch .aocf/cookie
          touch .aocf/config
          pwd
          ls -alh
          ls ..
          RUST_BACKTRACE=1 ./result/bin/day01 -b
          RUST_BACKTRACE=1 strace -f ./result/bin/day01 -b
          cat .aocf/cache/aoc2021_07.json
          RUST_BACKTRACE=1 strace -f ./result/bin/day07 -b
